/**
 * Media URL utilities
 * ────────────────────
 * Handles two URL types transparently:
 *
 *  • Legacy Cloudinary URLs  — res.cloudinary.com  (photos uploaded before S3 migration)
 *    Thumbnails generated on-the-fly via URL transformation params.
 *
 *  • New S3 / CloudFront URLs — your CloudFront domain  (photos uploaded after migration)
 *    Thumbnails pre-generated by Lambda and stored at thumbnails/{key}.jpg
 *
 * Nothing in the app needs to know which storage backend was used — just call
 * thumbnailUrl() or previewUrl() and you get the right thing.
 */

const CF = process.env.NEXT_PUBLIC_CLOUDFRONT_URL?.replace(/\/$/, '') ?? '';

// ── thumbnailUrl ──────────────────────────────────────────────────────────────
/**
 * Returns a ~400×400 thumbnail URL suitable for tile and list views.
 *
 * For images the thumbnail is a cropped JPEG — typically 15–50 KB vs the
 * 5–20 MB original, making the gallery dramatically faster to load.
 *
 * For videos the thumbnail is a JPEG of the first frame — no <video> tags
 * in the grid means zero buffering overhead for 100s of video tiles.
 */
export function thumbnailUrl(url: string, mediaType?: 'photo' | 'video'): string {
  if (!url) return url;

  // ── S3 / CloudFront path ───────────────────────────────────────────────────
  if (CF && url.startsWith(CF)) {
    // e.g. https://abc.cloudfront.net/eventId/media/uuid.mp4
    //   →  https://abc.cloudfront.net/eventId/thumbnail/uuid.jpg
    return url
      .replace('/media/', '/thumbnail/')
      .replace(/\.[^/.]+$/, '.jpg');
  }

  // ── Legacy Cloudinary URL ──────────────────────────────────────────────────
  if (url.includes('res.cloudinary.com')) {
    if (mediaType === 'video') {
      return url
        .replace('/video/upload/', '/video/upload/c_fill,w_400,h_400,q_auto,f_jpg,so_0/')
        .replace(/\.[^/.]+$/, '.jpg');
    }
    return url.replace('/image/upload/', '/image/upload/c_fill,w_400,h_400,q_auto,f_auto/');
  }

  return url;
}

// ── previewUrl ────────────────────────────────────────────────────────────────
/**
 * Returns an optimised URL for the full-screen modal.
 *
 * S3/CloudFront: serves the original (CloudFront caches it at the edge anyway).
 * Cloudinary:    applies c_limit,w_1920 — typically 5–20× smaller than the raw
 *                original while being indistinguishable at screen size.
 * Videos:        always return the original URL (played by the browser natively).
 */
export function previewUrl(url: string, mediaType?: 'photo' | 'video'): string {
  if (!url || mediaType === 'video') return url;

  // S3 originals are served via CloudFront at original quality — no transform needed
  if (CF && url.startsWith(CF)) return url;

  // Legacy Cloudinary: cap at 1920px wide, auto quality + format
  if (url.includes('res.cloudinary.com')) {
    return url.replace('/image/upload/', '/image/upload/c_limit,w_1920,q_auto,f_auto/');
  }

  return url;
}
